language: android   # 声明构建语言环境
# dist: trusty

# notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置 false 吧
  # email: false

sudo: false         # sudo 权限

android:            # 配置信息
  components:
    - platform-tools
    - tools
    - build-tools-27.1.1              
    - android-27             
    - android-22
    - extra-android-m2repository     # Android Support Repository
    # - extra-google-m2repository
    - extra-android-support          # Support Library

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-27
    - sys-img-armeabi-v7a-android-22
    # - sys-img-x86-android-17

  # licenses:
  #  - 'android-sdk-license-.+'

# env:
  # global:
   # install timeout in minutes (2 minutes by default)
    # - ADB_INSTALL_TIMEOUT=8

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:              # 执行:下面的命令
  - android list target
  - chmod +x gradlew  # 改变 gradlew 的访问权限
  - ./gradlew test
  - ./gradlew connectedAndroidTest
  # - ./gradlew assembleRelease

# before_deploy:       # 部署之前
  # 使用 mv 命令进行修改 apk 文件的名字
  # - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/buff.apk

# before_install:
#  - chmod +x gradlew  # 改变 gradlew 的访问权限

# deploy:              # 部署
#   provider: releases # 部署到 GitHub Release，除此之外，Travis CI 还支持发布到 fir.im、AWS、Google App Engine 等
#   api_key:           # 填写 GitHub 的 token （Settings -> Personal access tokens -> Generate new token）
#     secure: 7f4dc45a19f742dce39cbe4d1e5852xxxxxxxxx 
#   file: app/build/outputs/apk/app-release.apk   # 部署文件路径
#   skip_cleanup: true     # 设置为 true 以跳过清理,不然 apk 文件就会被清理
#   on:     # 发布时机           
#     tags: true       # tags 设置为 true 表示只有在有 tag 的情况下才部署